experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train_mapped.tsv
    validation_path: ../data/{0}/val_mapped.tsv
    test_path: ../data/{0}/test_mapped.tsv
    side_information:
      - dataloader: VisualAttribute
        visual_features: ../data/{0}/PHI35_eos_embeddings_2025_03_31_18_32_03_indexed
  dataset: baby
  top_k: 20
  evaluation:
    cutoffs: 20
    simple_metrics: [Recall, nDCG, HR]
    relevance_threshold: 4
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.VBPR:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 10
        validation_metric: Recall@20
        restore: False
      lr:  [0.0001, 0.0005, 0.001, 0.005, 0.01]
      modalities: ('visual', )
      epochs: 200
      factors: [64, 128, 256]
      batch_size: 1024
      l_w: [0.01, 0.1]
      loaders: ('VisualAttribute',)
      seed: 123
    external.BM3:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: True
        validation_rate: 10
        validation_metric: Recall@20
        restore: False
      lr: [0.0001, 0.0005, 0.001, 0.005, 0.01]
      factors: [64, 128, 256]
      reg_weight: [0.01, 0.1]
      cl_weight: 2.0
      dropout: 0.3
      n_layers: 2
      modalities: ('visual', )
      loaders: ('VisualAttribute', )
      epochs: 200
      lr_sched: (1.0,50)
      batch_size: 1024
      seed: 123
    external.FREEDOM:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 10
        validation_metric: Recall@20
        restore: False
      lr:  [0.0001, 0.0005, 0.001, 0.005, 0.01]
      modalities: ('visual', )
      epochs: 200
      batch_size: 1024
      l_w: [0.01, 0.1]
      n_layers: 1
      n_ui_layers: 2
      top_k: 10
      factors: [64, 128, 256]
      mw: (0.1,0.9)
      drop: 0.8
      lr_sched: (1.0,50)
      loaders: ('VisualAttribute',)
      seed: 123
    external.LATTICE:
      meta:
        verbose: True
        save_weights: False
        save_recs: True
        validation_rate: 200
        validation_metric: Recall@20
        restore: False
      epochs: 200
      batch_size: 1024
      factors: [64, 128, 256]
      lr:  [0.0001, 0.0005, 0.001, 0.005, 0.01]
      l_w: [0.01, 0.1]
      n_layers: 1
      n_ui_layers: 2
      top_k: 10
      l_m: 0.7
      modalities: ('visual', )
      seed: 123