experiment:
  dataset: clothing
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train_mapped.tsv
    test_path: ../data/{0}/test_mapped.tsv
    validation_path: ../data/{0}/val_mapped.tsv
    side_information:
      - dataloader: ItemAttributesOH
        attribute_file: ../data/{0}/clothing_qwen2vl_onehot_mapped.tsv
  top_k: 20
  evaluation:
    cutoffs: 20
    simple_metrics: [Recall, nDCG, HR]
    relevance_threshold: 4
  external_models_path: ../external/models/__init__.py
  models:
    Random:
      meta:
        save_recs: False
      random_seed: 42
    MostPop:
      meta:
        verbose: True
        save_recs: False
    ItemKNN:
      meta:
        save_recs: False
        verbose: True
        hyper_max_evals: 30
        hyper_opt_alg: tpe
        validation_metric: Recall@20
      neighbors: [uniform, 5, 1000]
      asymmetric_alpha: [uniform, 0, 2]
      tversky_alpha: [uniform, 0, 2]
      tversky_beta: [uniform, 0, 2]
      similarity: [cosine, jaccard, dot, asym, tversky]
    AttributeItemKNN:
      meta:
        save_recs: False
        verbose: True
        hyper_max_evals: 30
        hyper_opt_alg: tpe
        validation_metric: Recall@20
      neighbors: [ uniform, 5, 1000 ]
      asymmetric_alpha: [uniform, 0, 2]
      tversky_alpha: [uniform, 0, 2]
      tversky_beta: [uniform, 0, 2]
      similarity: [cosine, jaccard, dot, asym, tversky]
      weight: [loguniform, -5, 5]
      feat_w: ["", "TF_IDF", "BM25"]
      loader: "ItemAttributesOH"
    BPRMF_batch:
      meta:
        hyper_max_evals: 30
        hyper_opt_alg: tpe
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 10
        validation_metric: Recall@20
        restore: False
      epochs: 200
      batch_size: 8192
      factors: [64, 128, 256]
      lr: [loguniform, -11.512925464970229, 0]
      l_w: [loguniform, -11.512925464970229, -2.30258509299]
      l_b: [loguniform, -11.512925464970229, -2.30258509299]
      seed: 123
    external.LightGCN:
      meta:
        hyper_max_evals: 30
        hyper_opt_alg: tpe
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 10
        validation_metric: Recall@20
        restore: False
      lr: [loguniform, -11.512925464970229, 0]
      epochs: 200
      n_layers: 3
      factors: [64, 128, 256]
      batch_size: 8192
      normalize: True
      l_w: [loguniform, -11.512925464970229, -2.30258509299]
      seed: 123